# fly.toml file generated for reactivities-api-app on 2023-04-07T11:06:15+02:00

app = "reactivities-api-app"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "cdg"

[build]
  image = "stnmboa/reactivities:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__Cloudname="dvyclpuks"
  Cloudinary__ApiKey="245423816678958"
  Facebook__AppId="934829381052107"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
