name: docker-push

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx #this will biuld a docker image for us
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} #this info will be store into gitHub/repoName/setings/security/secrets variable web site 
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: stnmboa/reactivities:latest